plugins {
    id 'com.android.application'
}

android {
    namespace 'com.daviverissimo_app.matemticautility'
    compileSdk 34

    defaultConfig {
        applicationId "com.daviverissimo_app.matemticautility"
        minSdk 21
        targetSdk 34
        versionCode 10
        versionName "classic 4"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    buildFeatures {
        viewBinding true
    }
}

dependencies {

    // AndroidX base
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.0'
    implementation 'androidx.fragment:fragment:1.8.9'

    // Lifecycle (substitui android.arch.lifecycle)
    implementation 'androidx.lifecycle:lifecycle-livedata:2.8.4'
    implementation 'androidx.lifecycle:lifecycle-viewmodel:2.8.4'

    // Navigation (substitui android.arch.navigation)
    implementation 'androidx.navigation:navigation-fragment:2.8.0'
    implementation 'androidx.navigation:navigation-ui:2.8.0'

    // Testes
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.2.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.6.1'
}
